//third party module
const bcrypt = require('bcrypt');
//Objectid
const { ObjectId } = require('mongodb');

//importing models
const Coupons = require('../model/coupon');


//coupon Generator
const couponGenerator = require('../utilities/coupongenerator')

module.exports = {

  //Function for coupon page rendering
  adminCouponPage: async (req, res) => {

    const couponCode = couponGenerator()//coupon code generated by couponGenerator function

    //pagination
    const page = req.query.page || 1
    const limit = 5
    const skip = (page - 1) * limit

    const message = req.flash('message');
    const coupons = await Coupons.find({})
      .skip(skip) // Skip the specified number of documents
      .limit(limit); // Limit the number of documents returned

    res.render('admin/coupon-page', { URL: 'coupons', message, coupons, couponCode });
  },

  //function to add coupon by admin
  addCoupon: async (req, res) => {
    //extracting datas from req.body
    let { coupon_code, minOrderAmount, discount, start_date, expire_date } = req.body

    try {
      //creating an instance of coupon
      const coupon = new Coupons({
        coupon_code,
        minOrderAmount,
        discount,
        start_date,
        expire_date
      })
      await coupon.save()

      req.flash('message', 'Coupon Added succesfully')//sending message in flash
      res.redirect('/admin/coupons')
    } catch (error) {
      //catch any error
      console.log(error)
    }

  },

  //function to edit coupon
  adminCouponEdit: async (req, res) => {
    const couponId = new ObjectId(req.params.couponId)//couponid from req.params

    try {

      //fetch the coupon from db using the couponid
      const coupon = await Coupons.findById(couponId)

      //render the page with the coupon details
      res.render('admin/coupon-edit', { coupon })
    } catch (error) {
      console.log(error)
    }

  },

  adminCouponEditPost: async (req, res) => {
    const couponId = new ObjectId(req.params.couponId)

    //extracting the values from req.body
    let { minOrderAmount, discount, start_date, expire_date } = req.body

    try {
      //find one and update the edits in database
      await Coupons.findOneAndUpdate(
        { _id: couponId },
        {
          $set: {
            minOrderAmount,
            discount,
            start_date,
            expire_date
          }
        }
      )
      req.flash('message', 'Coupon Edited Successfully')
      return res.redirect('/admin/coupons')
    } catch (error) {
      console.log(error)
    }

  },

  //Function to delete coupon  from the database
  adminCouponDelete: async (req, res) => {
    const couponId = new ObjectId(req.params.couponId);
    const couponDelete = await Coupons.findByIdAndDelete(couponId);
    req.flash('message', 'Coupon Deleted');
    res.redirect('/admin/coupons');
  },

}